server:
  port: 8000

spring:
  application:
    name: scg
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: user
          uri: http://localhost:8001
          predicates:
            - Path=/user/**